-- Base del modulo catalog/imports.
-- Separa el catalogo de competiciones y temporadas del runtime de la liga
-- fantasy, y deja preparada la trazabilidad para futuros imports CSV.

create table if not exists public.platform_user_roles (
    user_id uuid not null,
    role text not null,
    assigned_at timestamptz not null default timezone('utc', now()),
    assigned_by uuid null,
    notes text null,
    constraint platform_user_roles_pkey primary key (user_id, role),
    constraint platform_user_roles_role_check
        check (role in ('catalog_admin'))
);

create index if not exists idx_platform_user_roles_role
    on public.platform_user_roles (role);

create table if not exists public.catalog_competitions (
    id bigint generated by default as identity primary key,
    slug text not null unique,
    provider text not null default 'kaggle',
    source_competition_id integer not null,
    name text not null,
    country text null,
    tier integer null,
    sort_order integer not null default 0,
    is_active boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    constraint catalog_competitions_provider_source_unique
        unique (provider, source_competition_id)
);

create index if not exists idx_catalog_competitions_active_sort
    on public.catalog_competitions (is_active, sort_order, name);

create table if not exists public.catalog_seasons (
    season text primary key,
    sort_order integer not null,
    is_active boolean not null default true,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_catalog_seasons_active_sort
    on public.catalog_seasons (is_active, sort_order);

create table if not exists public.catalog_dataset_versions (
    id bigint generated by default as identity primary key,
    provider text not null default 'kaggle',
    version_key text not null unique,
    label text not null,
    source_type text not null default 'csv',
    source_filename text null,
    status text not null default 'published',
    created_by uuid null,
    created_at timestamptz not null default timezone('utc', now()),
    published_at timestamptz null,
    constraint catalog_dataset_versions_status_check
        check (status in ('draft', 'validated', 'published', 'archived'))
);

create index if not exists idx_catalog_dataset_versions_status
    on public.catalog_dataset_versions (status);

create table if not exists public.catalog_import_jobs (
    id bigint generated by default as identity primary key,
    dataset_version_id bigint null
        references public.catalog_dataset_versions (id)
        on delete set null,
    job_type text not null,
    status text not null default 'pending',
    filename text null,
    storage_path text null,
    checksum_sha256 text null,
    validation_summary jsonb not null default '{}'::jsonb,
    error_count integer not null default 0,
    created_by uuid null,
    created_at timestamptz not null default timezone('utc', now()),
    started_at timestamptz null,
    finished_at timestamptz null,
    constraint catalog_import_jobs_error_count_check check (error_count >= 0),
    constraint catalog_import_jobs_job_type_check
        check (job_type in ('csv_import', 'catalog_sync')),
    constraint catalog_import_jobs_status_check
        check (status in ('pending', 'validating', 'validated', 'failed', 'published', 'cancelled'))
);

create index if not exists idx_catalog_import_jobs_status_created_at
    on public.catalog_import_jobs (status, created_at desc);

create table if not exists public.catalog_import_job_errors (
    id bigint generated by default as identity primary key,
    job_id bigint not null
        references public.catalog_import_jobs (id)
        on delete cascade,
    row_number integer null,
    field_name text null,
    error_code text not null,
    message text not null,
    raw_payload jsonb null,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_catalog_import_job_errors_job_id
    on public.catalog_import_job_errors (job_id);

insert into public.catalog_seasons (season, sort_order, is_active)
values
    ('2008/2009', 10, true),
    ('2009/2010', 20, true),
    ('2010/2011', 30, true),
    ('2011/2012', 40, true),
    ('2012/2013', 50, true),
    ('2013/2014', 60, true),
    ('2014/2015', 70, true),
    ('2015/2016', 80, true)
on conflict (season) do update
set
    sort_order = excluded.sort_order,
    is_active = excluded.is_active;

insert into public.catalog_competitions (
    slug,
    provider,
    source_competition_id,
    name,
    country,
    tier,
    sort_order,
    is_active
)
values
    ('spain-liga-bbva', 'kaggle', 21518, 'Spain LIGA BBVA', 'Spain', 1, 10, true),
    ('england-premier-league', 'kaggle', 1729, 'England Premier League', 'England', 1, 20, true),
    ('germany-bundesliga', 'kaggle', 7809, 'Germany Bundesliga', 'Germany', 1, 30, true)
on conflict (provider, source_competition_id) do update
set
    slug = excluded.slug,
    name = excluded.name,
    country = excluded.country,
    tier = excluded.tier,
    sort_order = excluded.sort_order,
    is_active = excluded.is_active,
    updated_at = timezone('utc', now());

insert into public.catalog_dataset_versions (
    provider,
    version_key,
    label,
    source_type,
    source_filename,
    status,
    published_at
)
values (
    'kaggle',
    'legacy-bootstrap-v1',
    'Legacy bootstrap dataset',
    'csv',
    'players_15.csv',
    'published',
    timezone('utc', now())
)
on conflict (version_key) do update
set
    label = excluded.label,
    source_type = excluded.source_type,
    source_filename = excluded.source_filename,
    status = excluded.status;

alter table public.fantasy_leagues
    add column if not exists competition_id bigint null;

alter table public.fantasy_leagues
    add column if not exists dataset_version_id bigint null;

update public.fantasy_leagues fl
set competition_id = cc.id
from public.catalog_competitions cc
where fl.competition_id is null
  and cc.provider = 'kaggle'
  and cc.source_competition_id = fl.kaggle_league_id;

update public.fantasy_leagues fl
set dataset_version_id = dv.id
from public.catalog_dataset_versions dv
where fl.dataset_version_id is null
  and dv.version_key = 'legacy-bootstrap-v1';

create index if not exists idx_fantasy_leagues_competition_id
    on public.fantasy_leagues (competition_id);

create index if not exists idx_fantasy_leagues_dataset_version_id
    on public.fantasy_leagues (dataset_version_id);

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'fantasy_leagues_competition_id_fkey'
    ) then
        alter table public.fantasy_leagues
            add constraint fantasy_leagues_competition_id_fkey
            foreign key (competition_id)
            references public.catalog_competitions (id)
            on delete set null;
    end if;
end $$;

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'fantasy_leagues_dataset_version_id_fkey'
    ) then
        alter table public.fantasy_leagues
            add constraint fantasy_leagues_dataset_version_id_fkey
            foreign key (dataset_version_id)
            references public.catalog_dataset_versions (id)
            on delete set null;
    end if;
end $$;
