-- Extiende el modulo catalog/imports con soporte para:
-- - plantilla de importacion
-- - filas normalizadas por job
-- - publicacion controlada

alter table public.catalog_import_jobs
    add column if not exists template_key text null;

alter table public.catalog_import_jobs
    add column if not exists published_at timestamptz null;

alter table public.catalog_import_jobs
    add column if not exists published_by uuid null;

create index if not exists idx_catalog_import_jobs_template_key
    on public.catalog_import_jobs (template_key);

create table if not exists public.catalog_import_job_rows (
    id bigint generated by default as identity primary key,
    job_id bigint not null
        references public.catalog_import_jobs (id)
        on delete cascade,
    row_number integer not null,
    is_valid boolean not null default false,
    raw_payload jsonb not null default '{}'::jsonb,
    normalized_payload jsonb null,
    created_at timestamptz not null default timezone('utc', now()),
    constraint catalog_import_job_rows_unique_row unique (job_id, row_number)
);

create index if not exists idx_catalog_import_job_rows_job_id
    on public.catalog_import_job_rows (job_id);

create index if not exists idx_catalog_import_job_rows_job_id_valid
    on public.catalog_import_job_rows (job_id, is_valid);
